<?xml version="1.0" encoding="utf-8"?><Database Name="CMS" Class="BsolutionDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=197.50.115.147;Initial Catalog=CMS;Persist Security Info=True;User ID=." SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="CMSConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Bank_Name" Member="Bank_Names">
    <Type Name="Bank_Name">
      <Column Name="BankName_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Bank_Name" Member="Bank_Name1" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="DateOfOpen" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="AccountNo" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Loation" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="PersonInCharge" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Phone_PersonInCharge" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Bank_Name_Notes" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="RecTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsDisable" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Cash_Type" Member="Cash_Types">
    <Type Name="Cash_Type">
      <Column Name="Cash_Type_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Cash_Type_Name" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Cash_Type_Rectime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Cash_Type_Notes" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Rectime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsDisable" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Contat_T" Member="Contat_Ts">
    <Type Name="Contat_T">
      <Column Name="Contat_T_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Contat_T_Name" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Contat_T_RecTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Contat_T_Note" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="UserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Rectime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsDisable" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DiscountInvoice" Member="DiscountInvoice2s">
    <Type Name="DiscountInvoice2">
      <Column Name="DiscountInvoice_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Invoice_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DiscountInvoice_Percentage" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="DiscountInvoice_Amount" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="DiscountInvoice_Date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DiscountInvoice_Notes" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="DiscountInvoice_RecTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsFromCollecting" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Rectime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsDisable" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Expenses_Type" Member="Expenses_Types">
    <Type Name="Expenses_Type">
      <Column Name="Expenses_Type_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Expenses_Type_Name" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Expenses_Type_Rectime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Rectime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsDisable" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Invoice_Details" Member="Invoice_Details">
    <Type Name="Invoice_Detail">
      <Column Name="Invoice_Details_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Invoice_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Item_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Unit_Cost" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Total_Cost" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Total_Price" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="After_Disount_Price" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Rectime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsDisable" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Invoice_Serial_Collect" Member="Invoice_Serial_Collects">
    <Type Name="Invoice_Serial_Collect">
      <Column Name="Invoice_Serial_Collect_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Invoice_Serial_Collect_Collecting" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="USerID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LAstModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Invoice" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Collecting" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsDisable" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Invoice_T" Member="Invoice_Ts">
    <Type Name="Invoice_T">
      <Column Name="Invoice_T_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Invoice_T_Name" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Invoice_T_Rectime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Invoice_T_Note" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Invoice_T_PayOrGain" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Rectime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsDisable" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.InvoiceTax" Member="InvoiceTaxes">
    <Type Name="InvoiceTax">
      <Column Name="InvoiceTax_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="InvoiceTax_Percentage" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="InvoiceTax_Amount" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Invoice_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Tax_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="InvoiceTax_RecTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Rectime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsDisable" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Item_Type" Member="Item_Types">
    <Type Name="Item_Type">
      <Column Name="Item_Type" Member="Item_Type1" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Item_Type_Name" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RecTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Item_Type_Notes" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="IsDisable" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Items" Member="Items">
    <Type Name="Item">
      <Column Name="Items_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Items_Name" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Items_Notes" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Items_Price" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Contact_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Type_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="User_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RecTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="HasStock" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AverageCost" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="IsDisable" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Stock" Member="Stocks">
    <Type Name="Stock">
      <Column Name="Stock_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Stock_Quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LastModifyDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Last_UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Item_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsDisable" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tax" Member="Taxes">
    <Type Name="Tax">
      <Column Name="Tax_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Tax_Name" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Tax_Percentage" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="IsDisable" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Tax_RecTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Tax_Notes" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Rectime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsDisable2" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Total_Transation" Member="Total_Transations">
    <Type Name="Total_Transation">
      <Column Name="Total_Transation_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Total_Transation_Month" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Total_Transation_Year" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TotalInvoiceGain" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="TotalInvoicePay" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="TotalCollectingPay" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="TotalCollectingGain" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="TotalExpenses" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Rectime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsDisable" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Transaction_Details" Member="Transaction_Details">
    <Type Name="Transaction_Detail">
      <Column Name="Transaction_Details_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Transaction_Details_Name" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Transaction_Type_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Transaction_Details_Date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Transaction_Details_Cost" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Transaction_Details_Price" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Original_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Transaction_Details_Profit" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Transaction_Details_Notes" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Transaction_Details_UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Transaction_Details_Rectime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Rectime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsDisable" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Transaction_Type" Member="Transaction_Types">
    <Type Name="Transaction_Type">
      <Column Name="Transaction_Type_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Transaction_Type_Name" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Transaction_Type_UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Transaction_Type_RecTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Transaction_Type_Notes" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Rectime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsDisable" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Cash" Member="Cashes">
    <Type Name="Cash">
      <Column Name="Cash_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Collecting_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="true" />
      <Column Name="Cash_Amount" Type="System.Single" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Cash_Date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="PersonInCharge" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Operation_Type" Type="System.Int32" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Cash_Notes" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Cash_RecTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Expenses_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="true" />
      <Column Name="Rectime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsDisable" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CashID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Bank" Member="Banks">
    <Type Name="Bank">
      <Column Name="Bank_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BankName_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Collecting_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Amount" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="DateTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="PersonInCharge" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Operation_Type" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Bank_Notes" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="RecTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Expenses_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsDisable" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Cheque" Member="Cheques">
    <Type Name="Cheque">
      <Column Name="Cheque_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Cheque_No" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Cheque_Date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="PersonInCharge" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RecTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Done" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Cheque_Bank_Name" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Cheque_Notes" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="IsDisable" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Collecting_Id" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Collecting" Member="Collectings">
    <Type Name="Collecting">
      <Column Name="Collecting_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Collecting_Name" Type="System.String" DbType="NVarChar(350) NOT NULL" CanBeNull="false" />
      <Column Name="Collecting_No" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Collecting_Date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Invoice_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Collecting_Amount" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Collecting_WhatsLeft" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Collecting_Rectime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Collecting_Note" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Cheque_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Contact_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="User_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Log_Date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Operation_Type_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Rectime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsDisable" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="BankorCash" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Scripts" Member="Scripts">
    <Type Name="Script">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Query" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Invoice" Member="Invoices">
    <Type Name="Invoice">
      <Column Name="Invoice_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Invoice_No" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Invoice_Date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Contact_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Invoice_Type_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Invoice_Rectime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Invoice_Note" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Invoice_TotalCost" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Invoice_IsDone" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Invoice_Price" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Invoice_AfterDiscountprice" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Invoice_AfterDiscountprice_ATax" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Rectime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsDisable" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="totalPrice" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Expenses" Member="Expenses">
    <Type Name="Expense">
      <Column Name="Expenses_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Expenses_Type_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Expenses_No" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Expenses_Date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Expenses_Cost" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Expenses_Quantity" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Expenses_Total" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Expenses_From" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Expenses_PersonInCharge" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Expenses_Rectime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Rectime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsDisable" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(900)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Contact" Member="Contact2s">
    <Type Name="Contact2">
      <Column Name="Contact_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Contact_Name" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Contact_Mobile" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Contact_Location" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Contact_Phone" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Contact_Website" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Contact_Note" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Client_Type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Contact_Rectime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Contact_ManinCharge" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Contact_Mobile_ManinChaarge" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Rectime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsDisable" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="AccountID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="password" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ISDisable" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsAdmin" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PagewUser" Member="PagewUsers">
    <Type Name="PagewUser">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="pageID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="userid" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Pages" Member="Page2s">
    <Type Name="Page2">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PageName" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="URL" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="ISAll" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(400)" CanBeNull="true" />
    </Type>
  </Table>
</Database>